theme: jekyll-theme-hacker
title: Sang Tan Nguyen's Homepage
logo: /assets/img/CV_Pic.JPG
description: Bookmark this to keep an eye on my project updates!
email: sangnt1321@gmail.com
social_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/sang-nguyen-tan-103319329/